### ISSUE TITLE
Is this working?

### ISSUE THREAD

**Issue by davux** [mekucuker/keycloak-query-param-token-mapper#1]
Hello, thanks for the very useful extension.

I noticed the code is 2 years old. Does this work out-of-the-box with recent versions of Keycloak? I'm trying to configure it but the token doesn't contain the value of the query parameter.

Thanks!

**Comment by mekucuker** [comment]
Hello,

Yes, it's working. It was developed for Keycloak version 16, but it was also a feature we have used in version 22. I'm not sure about the latest versions, but if you're getting a build error, there may have been changes in the interfaces.

As I recall, this provider allowed you to define a mapper under a ‘client scope’. Therefore, the authorization request should be sent with the relevant scope parameter. If everything is correct, the query parameter added to the authorization request URL that matches the mapper you defined should result in the claim being added to the token content.

I hope this helps.

**Comment by davux** [comment]
Thanks @mekucuker, it is in fact working. I was forming the request incorrectly. So I confirm it works with latest Keycloak version!

Thanks again for the library, it's very useful, the code is pretty, and I think more people should know about it.
